### ISSUE TITLE
Receiving error about classpath 

### ISSUE THREAD

**Issue by GlennOlsson** [slarse/repomate-junit4#29]
When trying to run 
`repomate -p junit4 clone -mn WEEK -rtd TEST-DIRECTORY -v`
I receive 
`[ERROR] _ActException: HookResult(hook='junit4', status=<Status.ERROR: 'error'>, msg='junit-4.12.jar not on the classpath')`
Even though the classpath is set correctly

**Comment by slarse** [comment]
It appears to work fine in`0.3.1`, but breaks in `0.4.0`. So something in the `0.4.0` update broke this functionality.

**Comment by slarse** [comment]
Alright, this is very likely due to a stupid regex error introduced with the new security policy.

https://github.com/slarse/repomate-junit4/blob/fb89fc178030d08b20f885f1c03779c4e69f541b/repomate_junit4/_junit4_runner.py#L55-L57

This regex only finds the jar if it is not the first, nor the last, element on the classpath. This regex is pretty darn broken, but it's an easy fix.
